# Railway.app deployment configuration
# Place this in your project root for Railway deployment

# Railway automatically detects Dockerfile and docker-compose files
# This file provides Railway-specific environment variables and settings

# Build Configuration
build:
  dockerfile: Dockerfile

# Environment Variables for Railway
environment:
  ASPNETCORE_ENVIRONMENT: Production
  ASPNETCORE_URLS: http://+:$PORT
  
  # Railway provides DATABASE_URL automatically for PostgreSQL addon
  # Our app will use DATABASE_PUBLIC_URL or fallback to DATABASE_URL
  DATABASE_PUBLIC_URL: $DATABASE_URL
  
  # Required: Set these in Railway dashboard
  JWT_SECRET_KEY: $JWT_SECRET_KEY
  
  # Optional: Customize these in Railway dashboard
  FRONTEND_URL: $FRONTEND_URL
  CORS__AllowedOrigins__0: $FRONTEND_URL

# Health Check Configuration
healthcheck:
  path: /health
  interval: 30s
  timeout: 10s
  retries: 3

# Resource Configuration
resources:
  memory: 512
  cpu: 0.25

# Port Configuration
port: $PORT

# Restart Policy
restart: unless-stopped
