# Railway deployment configuration
# Railway will auto-detect Dockerfile and build the container

[build]
builder = "dockerfile"

[deploy]
startCommand = "dotnet PersonalFinanceAPI.dll"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

# Environment variables for deployment
[experimental]
configAsCode = true
