# Railway deployment configuration
# Railway will auto-detect Dockerfile and build the container

[build]
builder = "dockerfile"

[deploy]
startCommand = "dotnet PersonalFinanceAPI.dll"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

# Environment variables for deployment
[experimental]
configAsCode = true

# Set environment variables
[environments.production.variables]
ASPNETCORE_ENVIRONMENT = "Production"
ASPNETCORE_URLS = "http://0.0.0.0:$PORT"
