// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PersonalFinanceAPI.Infrastructure.Data;

#nullable disable

namespace PersonalFinanceAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250812193202_AddOccupationAndCurrencyToUser")]
    partial class AddOccupationAndCurrencyToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PersonalFinanceAPI.Models.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<string>("NewValuesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_values");

                    b.Property<string>("OldValuesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_values");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("audit_logs");
                });

            modelBuilder.Entity("PersonalFinanceAPI.Models.Entities.BankAggregator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApiEndpoint")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("api_endpoint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("bank_aggregators");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6a8b7ff9-99b5-4fd7-a7c8-cf4551100dc5"),
                            ApiEndpoint = "https://api.demo-bank.com",
                            CreatedAt = new DateTime(2025, 8, 12, 19, 31, 59, 645, DateTimeKind.Utc).AddTicks(1104),
                            IsActive = true,
                            Name = "Demo Bank Connector",
                            UpdatedAt = new DateTime(2025, 8, 12, 19, 31, 59, 645, DateTimeKind.Utc).AddTicks(1105)
                        },
                        new
                        {
                            Id = new Guid("62306dba-9063-433d-81fd-e91867630d49"),
                            ApiEndpoint = "https://api.openbanking-sim.com",
                            CreatedAt = new DateTime(2025, 8, 12, 19, 31, 59, 645, DateTimeKind.Utc).AddTicks(1112),
                            IsActive = true,
                            Name = "Simulated Open Banking",
                            UpdatedAt = new DateTime(2025, 8, 12, 19, 31, 59, 645, DateTimeKind.Utc).AddTicks(1113)
                        });
                });

            modelBuilder.Entity("PersonalFinanceAPI.Models.Entities.Budget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BudgetAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("budget_amount");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("CurrentSpent")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("current_spent");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PeriodType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("period_type");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("budgets");
                });

            modelBuilder.Entity("PersonalFinanceAPI.Models.Entities.BudgetUtilization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AmountUtilized")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount_utilized");

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("uuid")
                        .HasColumnName("budget_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.Property<DateOnly>("UtilizationDate")
                        .HasColumnType("date")
                        .HasColumnName("utilization_date");

                    b.HasKey("Id");

                    b.HasIndex("BudgetId");

                    b.HasIndex("TransactionId");

                    b.ToTable("budget_utilizations");
                });

            modelBuilder.Entity("PersonalFinanceAPI.Models.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("icon");

                    b.Property<bool>("IsSystemDefined")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system_defined");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4c4d8137-c0db-4b12-8697-cac2646d1c2b"),
                            Color = "#FF6B6B",
                            CreatedAt = new DateTime(2025, 8, 12, 19, 31, 59, 645, DateTimeKind.Utc).AddTicks(115),
                            Icon = "restaurant",
                            IsSystemDefined = true,
                            Name = "Food & Dining",
                            Type = "EXPENSE",
                            UpdatedAt = new DateTime(2025, 8, 12, 19, 31, 59, 645, DateTimeKind.Utc).AddTicks(116)
                        },
                        new
                        {
                            Id = new Guid("2ab3b432-71f0-4d0a-9cc7-db52f2b8be3c"),
                            Color = "#4ECDC4",
                            CreatedAt = new DateTime(2025, 8, 12, 19, 31, 59, 645, DateTimeKind.Utc).AddTicks(125),
                            Icon = "car",
                            IsSystemDefined = true,
                            Name = "Transportation",
                            Type = "EXPENSE",
                            UpdatedAt = new DateTime(2025, 8, 12, 19, 31, 59, 645, DateTimeKind.Utc).AddTicks(126)
                        },
                        new
                        {
                            Id = new Guid("f90d138c-c9c3-47dd-bc17-25a3a9c3e63d"),
                            Color = "#45B7D1",
                            CreatedAt = new DateTime(2025, 8, 12, 19, 31, 59, 645, DateTimeKind.Utc).AddTicks(134),
                            Icon = "shopping-cart",
                            IsSystemDefined = true,
                            Name = "Shopping",
                            Type = "EXPENSE",
                            UpdatedAt = new DateTime(2025, 8, 12, 19, 31, 59, 645, DateTimeKind.Utc).AddTicks(135)
                        },
                        new
                        {
                            Id = new Guid("689dc3ce-bdef-4446-8d41-9b5e061da701"),
                            Color = "#96CEB4",
                            CreatedAt = new DateTime(2025, 8, 12, 19, 31, 59, 645, DateTimeKind.Utc).AddTicks(298),
                            Icon = "movie",
                            IsSystemDefined = true,
                            Name = "Entertainment",
                            Type = "EXPENSE",
                            UpdatedAt = new DateTime(2025, 8, 12, 19, 31, 59, 645, DateTimeKind.Utc).AddTicks(299)
                        },
                        new
                        {
                            Id = new Guid("a089ab47-fcf9-471f-a937-57017204f471"),
                            Color = "#FFEAA7",
                            CreatedAt = new DateTime(2025, 8, 12, 19, 31, 59, 645, DateTimeKind.Utc).AddTicks(306),
                            Icon = "receipt",
                            IsSystemDefined = true,
                            Name = "Bills & Utilities",
                            Type = "EXPENSE",
                            UpdatedAt = new DateTime(2025, 8, 12, 19, 31, 59, 645, DateTimeKind.Utc).AddTicks(307)
                        },
                        new
                        {
                            Id = new Guid("add7ad65-2c2a-46ee-83eb-0416f44632bf"),
                            Color = "#DDA0DD",
                            CreatedAt = new DateTime(2025, 8, 12, 19, 31, 59, 645, DateTimeKind.Utc).AddTicks(315),
                            Icon = "medical",
                            IsSystemDefined = true,
                            Name = "Healthcare",
                            Type = "EXPENSE",
                            UpdatedAt = new DateTime(2025, 8, 12, 19, 31, 59, 645, DateTimeKind.Utc).AddTicks(316)
                        },
                        new
                        {
                            Id = new Guid("a0f3ea59-e4c6-4806-8143-d96ebc4b583f"),
                            Color = "#98D8C8",
                            CreatedAt = new DateTime(2025, 8, 12, 19, 31, 59, 645, DateTimeKind.Utc).AddTicks(322),
                            Icon = "graduation-cap",
                            IsSystemDefined = true,
                            Name = "Education",
                            Type = "EXPENSE",
                            UpdatedAt = new DateTime(2025, 8, 12, 19, 31, 59, 645, DateTimeKind.Utc).AddTicks(323)
                        },
                        new
                        {
                            Id = new Guid("250e2952-639e-48e3-a234-5491ce25bbe7"),
                            Color = "#F7DC6F",
                            CreatedAt = new DateTime(2025, 8, 12, 19, 31, 59, 645, DateTimeKind.Utc).AddTicks(330),
                            Icon = "plane",
                            IsSystemDefined = true,
                            Name = "Travel",
                            Type = "EXPENSE",
                            UpdatedAt = new DateTime(2025, 8, 12, 19, 31, 59, 645, DateTimeKind.Utc).AddTicks(331)
                        },
                        new
                        {
                            Id = new Guid("0400c609-e7be-4a82-ab41-8be9b1e91af6"),
                            Color = "#2ECC71",
                            CreatedAt = new DateTime(2025, 8, 12, 19, 31, 59, 645, DateTimeKind.Utc).AddTicks(337),
                            Icon = "dollar-sign",
                            IsSystemDefined = true,
                            Name = "Salary",
                            Type = "INCOME",
                            UpdatedAt = new DateTime(2025, 8, 12, 19, 31, 59, 645, DateTimeKind.Utc).AddTicks(338)
                        },
                        new
                        {
                            Id = new Guid("a5323a77-5fa3-4f5b-be0c-f98524443e77"),
                            Color = "#27AE60",
                            CreatedAt = new DateTime(2025, 8, 12, 19, 31, 59, 645, DateTimeKind.Utc).AddTicks(345),
                            Icon = "briefcase",
                            IsSystemDefined = true,
                            Name = "Freelance",
                            Type = "INCOME",
                            UpdatedAt = new DateTime(2025, 8, 12, 19, 31, 59, 645, DateTimeKind.Utc).AddTicks(346)
                        },
                        new
                        {
                            Id = new Guid("3a567b23-0dba-4dd7-a114-037a764cb497"),
                            Color = "#16A085",
                            CreatedAt = new DateTime(2025, 8, 12, 19, 31, 59, 645, DateTimeKind.Utc).AddTicks(352),
                            Icon = "trending-up",
                            IsSystemDefined = true,
                            Name = "Investment Returns",
                            Type = "INCOME",
                            UpdatedAt = new DateTime(2025, 8, 12, 19, 31, 59, 645, DateTimeKind.Utc).AddTicks(353)
                        },
                        new
                        {
                            Id = new Guid("28ccd85e-4ffe-403b-a54c-803c2e17dec0"),
                            Color = "#95A5A6",
                            CreatedAt = new DateTime(2025, 8, 12, 19, 31, 59, 645, DateTimeKind.Utc).AddTicks(364),
                            Icon = "exchange",
                            IsSystemDefined = true,
                            Name = "Transfer",
                            Type = "TRANSFER",
                            UpdatedAt = new DateTime(2025, 8, 12, 19, 31, 59, 645, DateTimeKind.Utc).AddTicks(364)
                        });
                });

            modelBuilder.Entity("PersonalFinanceAPI.Models.Entities.FinancialGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("CurrentAmount")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("current_amount");

                    b.Property<string>("GoalName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("goal_name");

                    b.Property<string>("GoalType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("goal_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("PriorityLevel")
                        .HasColumnType("integer")
                        .HasColumnName("priority_level");

                    b.Property<decimal>("TargetAmount")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("target_amount");

                    b.Property<DateOnly?>("TargetDate")
                        .HasColumnType("date")
                        .HasColumnName("target_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("financial_goals");
                });

            modelBuilder.Entity("PersonalFinanceAPI.Models.Entities.IncomeEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("IncomeSourceId")
                        .HasColumnType("integer")
                        .HasColumnName("income_source_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_date");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference_number");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IncomeSourceId");

                    b.ToTable("income_entries");
                });

            modelBuilder.Entity("PersonalFinanceAPI.Models.Entities.IncomePlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("CurrentAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("current_amount");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<string>("PlanType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("plan_type");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("TargetAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("target_amount");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("income_plans");
                });

            modelBuilder.Entity("PersonalFinanceAPI.Models.Entities.IncomePlanMilestone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AchievedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("achieved_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<int>("IncomePlanId")
                        .HasColumnType("integer")
                        .HasColumnName("income_plan_id");

                    b.Property<bool>("IsAchieved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_achieved");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("TargetAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("target_amount");

                    b.Property<DateTime>("TargetDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("target_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IncomePlanId");

                    b.ToTable("income_plan_milestones");
                });

            modelBuilder.Entity("PersonalFinanceAPI.Models.Entities.IncomeSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ActualAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("actual_amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<decimal>("ExpectedAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("expected_amount");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("frequency");

                    b.Property<int>("IncomePlanId")
                        .HasColumnType("integer")
                        .HasColumnName("income_plan_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_type");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IncomePlanId");

                    b.ToTable("income_sources");
                });

            modelBuilder.Entity("PersonalFinanceAPI.Models.Entities.InvestmentSuggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("ExpectedReturnRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("expected_return_rate");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("InvestmentProduct")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("investment_product");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("PriorityScore")
                        .HasColumnType("integer")
                        .HasColumnName("priority_score");

                    b.Property<string>("Reasoning")
                        .HasColumnType("text")
                        .HasColumnName("reasoning");

                    b.Property<string>("RiskLevel")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("risk_level");

                    b.Property<decimal>("SuggestedAmount")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("suggested_amount");

                    b.Property<string>("SuggestionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("suggestion_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("investment_suggestions");
                });

            modelBuilder.Entity("PersonalFinanceAPI.Models.Entities.LinkedAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("account_name");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("account_number");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("account_type");

                    b.Property<decimal>("Balance")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("balance");

                    b.Property<Guid?>("BankAggregatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("bank_aggregator_id");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("bank_name");

                    b.Property<DateTime?>("ConsentExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consent_expires_at");

                    b.Property<DateTime>("ConsentGivenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consent_given_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<string>("ExternalAccountId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_account_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("BankAggregatorId");

                    b.HasIndex("UserId");

                    b.ToTable("linked_accounts");
                });

            modelBuilder.Entity("PersonalFinanceAPI.Models.Entities.Merchant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<string>("MccCode")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("mcc_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("merchants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4c3f8ad3-909e-4c76-8ca9-8d0c2eb9044a"),
                            CategoryId = new Guid("4c4d8137-c0db-4b12-8697-cac2646d1c2b"),
                            CreatedAt = new DateTime(2025, 8, 12, 19, 31, 59, 645, DateTimeKind.Utc).AddTicks(1216),
                            IsVerified = true,
                            MccCode = "5812",
                            Name = "Swiggy",
                            UpdatedAt = new DateTime(2025, 8, 12, 19, 31, 59, 645, DateTimeKind.Utc).AddTicks(1218)
                        },
                        new
                        {
                            Id = new Guid("0510e63d-05f6-471f-a982-2182d8925f1b"),
                            CategoryId = new Guid("4c4d8137-c0db-4b12-8697-cac2646d1c2b"),
                            CreatedAt = new DateTime(2025, 8, 12, 19, 31, 59, 645, DateTimeKind.Utc).AddTicks(1234),
                            IsVerified = true,
                            MccCode = "5812",
                            Name = "Zomato",
                            UpdatedAt = new DateTime(2025, 8, 12, 19, 31, 59, 645, DateTimeKind.Utc).AddTicks(1235)
                        },
                        new
                        {
                            Id = new Guid("b13bdae4-53c1-4019-b8bc-0dab1c66ce36"),
                            CategoryId = new Guid("2ab3b432-71f0-4d0a-9cc7-db52f2b8be3c"),
                            CreatedAt = new DateTime(2025, 8, 12, 19, 31, 59, 645, DateTimeKind.Utc).AddTicks(1243),
                            IsVerified = true,
                            MccCode = "4121",
                            Name = "Uber",
                            UpdatedAt = new DateTime(2025, 8, 12, 19, 31, 59, 645, DateTimeKind.Utc).AddTicks(1244)
                        },
                        new
                        {
                            Id = new Guid("70469cbd-6cb0-4a82-967c-5363fb371ec1"),
                            CategoryId = new Guid("f90d138c-c9c3-47dd-bc17-25a3a9c3e63d"),
                            CreatedAt = new DateTime(2025, 8, 12, 19, 31, 59, 645, DateTimeKind.Utc).AddTicks(1251),
                            IsVerified = true,
                            MccCode = "5399",
                            Name = "Amazon",
                            UpdatedAt = new DateTime(2025, 8, 12, 19, 31, 59, 645, DateTimeKind.Utc).AddTicks(1253)
                        },
                        new
                        {
                            Id = new Guid("ae30c3f8-8362-4e30-a8d5-33c5d0d92564"),
                            CategoryId = new Guid("689dc3ce-bdef-4446-8d41-9b5e061da701"),
                            CreatedAt = new DateTime(2025, 8, 12, 19, 31, 59, 645, DateTimeKind.Utc).AddTicks(1260),
                            IsVerified = true,
                            MccCode = "4899",
                            Name = "Netflix",
                            UpdatedAt = new DateTime(2025, 8, 12, 19, 31, 59, 645, DateTimeKind.Utc).AddTicks(1261)
                        },
                        new
                        {
                            Id = new Guid("fdb1d8a8-4287-4592-9d70-4bb2d6425def"),
                            CategoryId = new Guid("a089ab47-fcf9-471f-a937-57017204f471"),
                            CreatedAt = new DateTime(2025, 8, 12, 19, 31, 59, 645, DateTimeKind.Utc).AddTicks(1273),
                            IsVerified = true,
                            MccCode = "4900",
                            Name = "BSES Delhi",
                            UpdatedAt = new DateTime(2025, 8, 12, 19, 31, 59, 645, DateTimeKind.Utc).AddTicks(1274)
                        });
                });

            modelBuilder.Entity("PersonalFinanceAPI.Models.Entities.MonthlySummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AverageTransactionAmount")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("average_transaction_amount");

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_final");

                    b.Property<DateOnly>("MonthYear")
                        .HasColumnType("date")
                        .HasColumnName("month_year");

                    b.Property<decimal>("NetSavings")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("net_savings");

                    b.Property<decimal>("SavingsRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("savings_rate");

                    b.Property<decimal>("TopExpenseAmount")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("top_expense_amount");

                    b.Property<Guid?>("TopExpenseCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("top_expense_category_id");

                    b.Property<decimal>("TotalExpenses")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("total_expenses");

                    b.Property<decimal>("TotalIncome")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("total_income");

                    b.Property<int>("TransactionCount")
                        .HasColumnType("integer")
                        .HasColumnName("transaction_count");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TopExpenseCategoryId");

                    b.HasIndex("UserId", "MonthYear")
                        .IsUnique();

                    b.ToTable("monthly_summaries");
                });

            modelBuilder.Entity("PersonalFinanceAPI.Models.Entities.SuggestionHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("action");

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("action_date");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("SuggestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("suggestion_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("SuggestionId");

                    b.HasIndex("UserId");

                    b.ToTable("suggestion_history");
                });

            modelBuilder.Entity("PersonalFinanceAPI.Models.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("amount");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ExternalTransactionId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_transaction_id");

                    b.Property<bool>("IsCategorizedManually")
                        .HasColumnType("boolean")
                        .HasColumnName("is_categorized_manually");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("boolean")
                        .HasColumnName("is_recurring");

                    b.Property<bool>("IsTransfer")
                        .HasColumnType("boolean")
                        .HasColumnName("is_transfer");

                    b.Property<Guid>("LinkedAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_account_id");

                    b.Property<Guid?>("MerchantId")
                        .HasColumnType("uuid")
                        .HasColumnName("merchant_id");

                    b.Property<DateOnly?>("PostedDate")
                        .HasColumnType("date")
                        .HasColumnName("posted_date");

                    b.Property<string>("RawDataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_data");

                    b.Property<string>("RecurringFrequency")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("recurring_frequency");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("reference_number");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date")
                        .HasColumnName("transaction_date");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("transaction_type");

                    b.Property<Guid?>("TransferToAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("transfer_to_account_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("LinkedAccountId");

                    b.HasIndex("MerchantId");

                    b.HasIndex("TransferToAccountId");

                    b.HasIndex("UserId");

                    b.ToTable("transactions");
                });

            modelBuilder.Entity("PersonalFinanceAPI.Models.Entities.TransactionFlag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("FlagType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("flag_type");

                    b.Property<string>("FlagValue")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("flag_value");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("TransactionId");

                    b.ToTable("transaction_flags");
                });

            modelBuilder.Entity("PersonalFinanceAPI.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_email_verified");

                    b.Property<bool>("IsPhoneVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_phone_verified");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("Occupation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("occupation");

                    b.Property<string>("OtpCode")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("otp_code");

                    b.Property<DateTime?>("OtpExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("otp_expires_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("PersonalFinanceAPI.Models.Entities.UserAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at");

                    b.Property<string>("ActionUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("action_url");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("alert_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsActionable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_actionable");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("severity");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_alerts");
                });

            modelBuilder.Entity("PersonalFinanceAPI.Models.Entities.UserPreferences", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_code");

                    b.Property<decimal>("ExpenseThreshold")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("expense_threshold");

                    b.Property<string>("InvestmentRiskLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("investment_risk_level");

                    b.Property<bool>("NotificationEmail")
                        .HasColumnType("boolean")
                        .HasColumnName("notification_email");

                    b.Property<bool>("NotificationPush")
                        .HasColumnType("boolean")
                        .HasColumnName("notification_push");

                    b.Property<bool>("NotificationSms")
                        .HasColumnType("boolean")
                        .HasColumnName("notification_sms");

                    b.Property<decimal>("SavingsGoalMonthly")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("savings_goal_monthly");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("timezone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_preferences");
                });

            modelBuilder.Entity("PersonalFinanceAPI.Models.Entities.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessTokenJti")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("access_token_jti");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("RefreshToken")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("user_sessions");
                });

            modelBuilder.Entity("PersonalFinanceAPI.Models.Entities.AuditLog", b =>
                {
                    b.HasOne("PersonalFinanceAPI.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("PersonalFinanceAPI.Models.Entities.Budget", b =>
                {
                    b.HasOne("PersonalFinanceAPI.Models.Entities.Category", "Category")
                        .WithMany("Budgets")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PersonalFinanceAPI.Models.Entities.User", "User")
                        .WithMany("Budgets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PersonalFinanceAPI.Models.Entities.BudgetUtilization", b =>
                {
                    b.HasOne("PersonalFinanceAPI.Models.Entities.Budget", "Budget")
                        .WithMany("Utilizations")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonalFinanceAPI.Models.Entities.Transaction", "Transaction")
                        .WithMany("BudgetUtilizations")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Budget");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("PersonalFinanceAPI.Models.Entities.Category", b =>
                {
                    b.HasOne("PersonalFinanceAPI.Models.Entities.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("PersonalFinanceAPI.Models.Entities.FinancialGoal", b =>
                {
                    b.HasOne("PersonalFinanceAPI.Models.Entities.User", "User")
                        .WithMany("FinancialGoals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PersonalFinanceAPI.Models.Entities.IncomeEntry", b =>
                {
                    b.HasOne("PersonalFinanceAPI.Models.Entities.IncomeSource", "IncomeSource")
                        .WithMany("IncomeEntries")
                        .HasForeignKey("IncomeSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IncomeSource");
                });

            modelBuilder.Entity("PersonalFinanceAPI.Models.Entities.IncomePlan", b =>
                {
                    b.HasOne("PersonalFinanceAPI.Models.Entities.User", "User")
                        .WithMany("IncomePlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PersonalFinanceAPI.Models.Entities.IncomePlanMilestone", b =>
                {
                    b.HasOne("PersonalFinanceAPI.Models.Entities.IncomePlan", "IncomePlan")
                        .WithMany("Milestones")
                        .HasForeignKey("IncomePlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IncomePlan");
                });

            modelBuilder.Entity("PersonalFinanceAPI.Models.Entities.IncomeSource", b =>
                {
                    b.HasOne("PersonalFinanceAPI.Models.Entities.IncomePlan", "IncomePlan")
                        .WithMany("IncomeSources")
                        .HasForeignKey("IncomePlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IncomePlan");
                });

            modelBuilder.Entity("PersonalFinanceAPI.Models.Entities.InvestmentSuggestion", b =>
                {
                    b.HasOne("PersonalFinanceAPI.Models.Entities.User", "User")
                        .WithMany("InvestmentSuggestions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PersonalFinanceAPI.Models.Entities.LinkedAccount", b =>
                {
                    b.HasOne("PersonalFinanceAPI.Models.Entities.BankAggregator", "BankAggregator")
                        .WithMany("LinkedAccounts")
                        .HasForeignKey("BankAggregatorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PersonalFinanceAPI.Models.Entities.User", "User")
                        .WithMany("LinkedAccounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankAggregator");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PersonalFinanceAPI.Models.Entities.Merchant", b =>
                {
                    b.HasOne("PersonalFinanceAPI.Models.Entities.Category", "Category")
                        .WithMany("Merchants")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PersonalFinanceAPI.Models.Entities.MonthlySummary", b =>
                {
                    b.HasOne("PersonalFinanceAPI.Models.Entities.Category", "TopExpenseCategory")
                        .WithMany()
                        .HasForeignKey("TopExpenseCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PersonalFinanceAPI.Models.Entities.User", "User")
                        .WithMany("MonthlySummaries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TopExpenseCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PersonalFinanceAPI.Models.Entities.SuggestionHistory", b =>
                {
                    b.HasOne("PersonalFinanceAPI.Models.Entities.InvestmentSuggestion", "Suggestion")
                        .WithMany("History")
                        .HasForeignKey("SuggestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonalFinanceAPI.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Suggestion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PersonalFinanceAPI.Models.Entities.Transaction", b =>
                {
                    b.HasOne("PersonalFinanceAPI.Models.Entities.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PersonalFinanceAPI.Models.Entities.LinkedAccount", "LinkedAccount")
                        .WithMany("Transactions")
                        .HasForeignKey("LinkedAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PersonalFinanceAPI.Models.Entities.Merchant", "Merchant")
                        .WithMany("Transactions")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PersonalFinanceAPI.Models.Entities.LinkedAccount", "TransferToAccount")
                        .WithMany("TransferTransactions")
                        .HasForeignKey("TransferToAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PersonalFinanceAPI.Models.Entities.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("LinkedAccount");

                    b.Navigation("Merchant");

                    b.Navigation("TransferToAccount");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PersonalFinanceAPI.Models.Entities.TransactionFlag", b =>
                {
                    b.HasOne("PersonalFinanceAPI.Models.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PersonalFinanceAPI.Models.Entities.Transaction", "Transaction")
                        .WithMany("Flags")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("PersonalFinanceAPI.Models.Entities.UserAlert", b =>
                {
                    b.HasOne("PersonalFinanceAPI.Models.Entities.User", "User")
                        .WithMany("Alerts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PersonalFinanceAPI.Models.Entities.UserPreferences", b =>
                {
                    b.HasOne("PersonalFinanceAPI.Models.Entities.User", "User")
                        .WithOne("Preferences")
                        .HasForeignKey("PersonalFinanceAPI.Models.Entities.UserPreferences", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PersonalFinanceAPI.Models.Entities.UserSession", b =>
                {
                    b.HasOne("PersonalFinanceAPI.Models.Entities.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PersonalFinanceAPI.Models.Entities.BankAggregator", b =>
                {
                    b.Navigation("LinkedAccounts");
                });

            modelBuilder.Entity("PersonalFinanceAPI.Models.Entities.Budget", b =>
                {
                    b.Navigation("Utilizations");
                });

            modelBuilder.Entity("PersonalFinanceAPI.Models.Entities.Category", b =>
                {
                    b.Navigation("Budgets");

                    b.Navigation("Children");

                    b.Navigation("Merchants");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("PersonalFinanceAPI.Models.Entities.IncomePlan", b =>
                {
                    b.Navigation("IncomeSources");

                    b.Navigation("Milestones");
                });

            modelBuilder.Entity("PersonalFinanceAPI.Models.Entities.IncomeSource", b =>
                {
                    b.Navigation("IncomeEntries");
                });

            modelBuilder.Entity("PersonalFinanceAPI.Models.Entities.InvestmentSuggestion", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("PersonalFinanceAPI.Models.Entities.LinkedAccount", b =>
                {
                    b.Navigation("Transactions");

                    b.Navigation("TransferTransactions");
                });

            modelBuilder.Entity("PersonalFinanceAPI.Models.Entities.Merchant", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("PersonalFinanceAPI.Models.Entities.Transaction", b =>
                {
                    b.Navigation("BudgetUtilizations");

                    b.Navigation("Flags");
                });

            modelBuilder.Entity("PersonalFinanceAPI.Models.Entities.User", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Budgets");

                    b.Navigation("FinancialGoals");

                    b.Navigation("IncomePlans");

                    b.Navigation("InvestmentSuggestions");

                    b.Navigation("LinkedAccounts");

                    b.Navigation("MonthlySummaries");

                    b.Navigation("Preferences");

                    b.Navigation("Sessions");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
